---
title: "EvAnth_Final"
author: "Carly Levi"
date: "November 22, 2015"
output: html_document
---
```{r}
set.seed(83942)
library(ggplot2)
library(dplyr)
library(stringr)
```
 
```{r}
numloci<-10 #number of loci, feeblemindedness is a complex trait
eff<-rnorm(numloci,0,1) #effect size
numind<-1000 #number of individuals to sample
high<-2*sum(replace(eff,eff<0,0))
low<-2*sum(replace(eff,eff>0,0))
genomat <- matrix(NA, nrow = numind, ncol = numloci + 1)
pheno_df <- data.frame(phenos = rep(NA, numind))
for(i in 1:numind){
   geno<-replicate(numloci,sum(sample(c(0,1),2,replace=T)))
   genomat[i, 1:10]<-geno
   genomat[i,11] <- geno %*% eff
   pheno_df$phenos[i] <- geno %*% eff
}
 
hist(pheno_df$phenos,breaks = 100, main = '',xlab='phenotypic value',xlim=c(low-0.5,high+0.5))
abline(v=(-3.651707), col='red')
abline(v=(6.781549), col='red')
 
sd <- sd(pheno_df$phenos)
sd
 
mean <- mean(pheno_df$phenos)
mean
 
genomat2 <- as.data.frame(genomat)
 
feeble <- genomat2 %>% #gives number of feeble minded individuals and phenotype
  filter(genomat2[,11] < (mean - 2*sd))

high_function <- genomat2 %>% #gives number of high functioning individuals and phenotype
  filter(genomat2[,11] > (mean + 2*sd))

normal <- genomat2 %>% #gives number of normal individuals and phenotype
  filter(genomat2[,11] < (mean + 2*sd), genomat2[,11] > (mean - 2*sd))
```
 
```{r}
outcomes = c(0,1)
geno1 <- feeble[sample(nrow(feeble), numind,replace = TRUE),]
geno1<- as.data.frame(geno1)
geno1[geno1 == 0] <- 0
geno1[geno1 == 1] <- sample(c(0,1), 1, prob = c(.5,.5), replace = TRUE)
geno1[geno1 == 2] <- 1


geno2 <- feeble[sample(nrow(feeble), numind,replace = TRUE), ]
geno2 <- as.data.frame(geno2)
geno2[geno == 0] <- 0
geno2[geno1 == 2] <- sample(c(0,1), 1, prob = c(.5,.5), replace = TRUE)
geno2[geno1 == 2] <- 1

geno3 <- normal[sample(nrow(normal), numind,replace = TRUE),]
geno3 <- as.data.frame(geno3)
geno3[geno3 == 0] <- 0
geno3[geno3 == 1] <- sample(c(0,1), 1, prob = c(.5,.5), replace = TRUE)
geno3[geno3 == 2] <- 1

geno4 <- normal[sample(nrow(normal), numind,replace = TRUE), ]
geno4 <- as.data.frame(geno4)
geno4[geno4 == 0] <- 0
geno4[geno4 == 1] <- sample(c(0,1), 1, prob = c(.5,.5), replace = TRUE)
geno4[geno4 == 2] <- 1

geno5 <- high_function[sample(nrow(high_function), numind,replace = TRUE),]
geno5 <- as.data.frame(geno5)
geno5[geno5 == 0] <- 0
geno5[geno5 == 1] <- sample(c(0,1), 1, prob = c(.5,.5), replace = TRUE)
geno5[geno5 == 2] <- 1

geno6 <- high_function[sample(nrow(high_function), numind,replace = TRUE), ]
geno6 <- as.data.frame(geno6)
geno6[geno6 == 0] <- 0
geno6[geno6 == 1] <- sample(c(0,1), 1, prob = c(.5,.5), replace = TRUE)
geno6[geno6 == 2] <- 1

```
 
```{r}
pheno_feeble_feeble <- data.frame(phenos = rep(NA, numind))
pheno_feeble_normal <- data.frame(phenos = rep(NA, numind))
pheno_feeble_high <- data.frame(phenos = rep(NA, numind))
pheno_normal_normal <- data.frame(phenos = rep(NA, numind))
pheno_normal_high <- data.frame(phenos = rep(NA, numind))
pheno_high_high <- data.frame(phenos = rep(NA, numind))
```

```{r}
genokid_feeble_feeble <- matrix(rep(NA, numind*11), nrow = numind, ncol = numind + 1)
genokid_feeble_normal <- matrix(rep(NA, numind*11), nrow = numind, ncol = numind + 1)
genokid_feeble_high <- matrix(rep(NA, numind*11), nrow = numind, ncol = numind + 1)
genokid_normal_normal <- matrix(rep(NA, numind*11), nrow = numind, ncol = numind + 1)
genokid_normal_high <- matrix(rep(NA, numind*11), nrow = numind, ncol =  numind + 1)
genokid_high_high <- matrix(rep(NA, numind*11), nrow = numind, ncol = numind + 1)
```


```{r}
genokid_feeble_feeble <- geno1 + geno2
pheno_feeble_feeble$phenos <- genokid_feeble_feeble[,11]
#pheno_feeble_feeble

genokid_feeble_normal <- geno1 + geno3
pheno_feeble_normal$phenos <- genokid_feeble_normal[,11]
#pheno_feeble_normal

genokid_feeble_high <- geno1 + geno5
pheno_feeble_high$phenos <- genokid_feeble_high[,11]
#pheno_feeble_high

genokid_normal_normal <- geno3 + geno4
pheno_normal_normal$phenos <- genokid_normal_normal[,11]
#pheno_normal_normal 

genokid_normal_high <- geno3 + geno5
pheno_normal_high$phenos <- genokid_normal_high[,11]
#pheno_normal_high 

genokid_high_high <- geno5 + geno6
pheno_high_high$phenos <- genokid_high_high[,11]
#pheno_high_high
```

```{r feeble_feeble}
ggplot(data = pheno_feeble_feeble, aes(x = pheno_feeble_feeble$phenos)) +
  geom_histogram(binwidth =.2) +
  geom_vline(xintercept = -3.651707, color = "red") +
  xlab("Phenotypic Value")

below_sd_ff <- c()
for (i in pheno_feeble_feeble$phenos){
  if (i <= (mean-2*sd))
    below_sd_ff <- c(below_sd_ff, i)
}
prop_ff <- length(below_sd_ff) / numind
prop_ff
```

```{r feeble_normal}
ggplot(data = pheno_feeble_normal, aes(x = pheno_feeble_normal$phenos)) +
  geom_histogram(binwidth =.15) +
  geom_vline(xintercept = -3.651707, color = "red") +
  xlab("Phenotypic Value")

below_sd_fn <- c()
for (i in pheno_feeble_normal$phenos){
  if (i <= (-3.651707))
    below_sd_fn <- c(below_sd_fn, i)
}
prop_fn <- length(below_sd_fn) / numind
prop_fn
```

```{r feeble_high}
ggplot(data = pheno_feeble_high, aes(x = pheno_feeble_high$phenos)) +
  geom_histogram(binwidth =.2) +
  geom_vline(xintercept = -3.651707, color = "red") +
  xlab("Phenotypic Value")

below_sd_fh <- c()
for (i in pheno_feeble_high$phenos){
  if (i <= (-3.651707))
    below_sd_fh <- c(below_sd_fh, i)
}
prop_fh <- length(below_sd_fh) / numind
prop_fh
```

```{r normal_normal}
ggplot(data = pheno_normal_normal, aes(x = pheno_normal_normal$phenos)) +
  geom_histogram(binwidth =.2) +
  geom_vline(xintercept = -3.651707, color = "red") +
  xlab("Phenotypic Value")

below_sd_nn <- c()
for (i in pheno_normal_normal$phenos){
  if (i <= (-3.651707))
    below_sd_nn <- c(below_sd_nn, i)
}
prop_nn <- length(below_sd_nn) / numind
prop_nn
```

```{r normal_high}
ggplot(data = pheno_normal_high, aes(x = pheno_normal_high$phenos)) +
  geom_histogram(binwidth =.2) +
  geom_vline(xintercept = -3.651707, color = "red") +
  xlab("Phenotypic Value")

below_sd_nh <- c()
for (i in pheno_normal_high$phenos){
  if (i <= (-3.651707))
    below_sd_nh <- c(below_sd_nh, i)
}
prop_nh <- length(below_sd_nh) / numind
prop_nh
```

```{r high_high}
ggplot(data = pheno_high_high, aes(x = pheno_high_high$phenos)) +
  geom_histogram(binwidth =.2) +
  geom_vline(xintercept = -3.651707, color = "red") +
  xlab("Phenotypic Value")

below_sd_hh <- c()
for (i in pheno_high_high$phenos){
  if (i <= (-3.651707))
    below_sd_hh <- c(below_sd_hh, i)
}
prop_hh <- length(below_sd_hh) / numind
prop_hh
```

```{r}
#probability of child being feebleminded given that one parent is feebleminded

probability_kid1 <- prop_fh + prop_fn + prop_ff
probability_kid1

#not actually one, but very close because we have been using discrete values
```

```{r}
#probability of one parent being feebleminded given that their child is feebleminded

probability_parent <- (prop_fh + prop_fn + prop_ff) / (prop_ff + prop_hh + prop_nh + prop_nn + prop_fh + prop_fn)
probability_parent
```

